<?php
/**
 * One-off: merge missing French translations from EN + manual map.
 * Run: php scripts/sync_lang_fr.php
 */

$en = include __DIR__ . '/../resources/lang/en/file.php';
$frPath = __DIR__ . '/../resources/lang/fr/file.php';
$fr = include $frPath;

$manual = [
    'File' => 'Fichier',
    'File Type' => 'Type de fichier',
    'Add Musician' => 'Ajouter un musicien',
    'Add Musician Gallery' => 'Ajouter une galerie musicien',
    'Remarks' => 'Remarques',
    'Fixed Assets' => 'Immobilisations',
    'Fixed Assets Report' => 'Rapport des immobilisations',
    'Assets Dashboard' => 'Tableau de bord des actifs',
    'Assets Region' => 'Région des actifs',
    'Assets Station' => 'Station des actifs',
    'Assets Category' => 'Catégorie des actifs',
    'Add Assets Type' => 'Ajouter un type d\'actif',
    'Assets Type List' => 'Liste des types d\'actifs',
    'Assets Type' => 'Type d\'actif',
    'Add Assets' => 'Ajouter un actif',
    'Asset Information' => 'Informations sur l\'actif',
    'Asset Category Report' => 'Rapport par catégorie d\'actifs',
    'Asset Department Report' => 'Rapport par département d\'actifs',
    'Asset Donor Report' => 'Rapport par donateur d\'actifs',
    'Asset Region Report' => 'Rapport par région d\'actifs',
    'Asset Station Report' => 'Rapport par station d\'actifs',
    'Assets List' => 'Liste des actifs',
    'Physical Location' => 'Emplacement physique',
    'Life Span' => 'Durée de vie',
    'Purchase Date' => 'Date d\'achat',
    'Region' => 'Région',
    'Station' => 'Station',
    'Donor' => 'Donateur',
    'Category' => 'Catégorie',
    'Asset Type' => 'Type d\'actif',
    'Asset Activity' => 'Activité de l\'actif',
    'Asset Expense' => 'Dépense de l\'actif',
    'Edit Station' => 'Modifier la station',
    'Add Station' => 'Ajouter une station',
    'Assets Donor' => 'Donateur d\'actifs',
    'Add Donor' => 'Ajouter un donateur',
    'Add Region' => 'Ajouter une région',
    'Edit Region' => 'Modifier la région',
    'Donor List' => 'Liste des donateurs',
    'Station List' => 'Liste des stations',
    'Region List' => 'Liste des régions',
    'Assets Report' => 'Rapport des actifs',
    'Add Asset Category' => 'Ajouter une catégorie d\'actif',
    'Asset Category List' => 'Liste des catégories d\'actifs',
    'Product Category' => 'Catégorie de produit',
    'Choose Account' => 'Choisir un compte',
    'Asset Expense & Activity' => 'Dépenses et activités des actifs',
    'Activity & Expense Report' => 'Rapport activités et dépenses',
    'Add Asset Expense' => 'Ajouter une dépense d\'actif',
    'Add Activity Expense' => 'Ajouter une dépense d\'activité',
    'Customer Name' => 'Nom du client',
    'Booking Module' => 'Module de réservation',
    'Letters' => 'Courriers',
    'Reference' => 'Référence',
    'Send' => 'Envoyer',
    'Letter Serial No.' => 'N° de série du courrier',
    'Action' => 'Action',
    'Sign' => 'Signer',
    'Signed By' => 'Signé par',
    'Sent By' => 'Envoyé par',
    'Stemp' => 'Commentaire',
    'Edit By' => 'Modifié par',
    'Author Name' => 'Nom de l\'auteur',
    'Update Letter' => 'Mettre à jour le courrier',
    'Is Template' => 'Est un modèle',
    'Approved By' => 'Approuvé par',
    'Header' => 'En-tête',
    'Subject' => 'Objet',
    'Body' => 'Corps',
    'Footer' => 'Pied de page',
    'Letters List' => 'Liste des courriers',
    'CC' => 'CC',
    'Letter Template' => 'Modèle de courrier',
    'Letter Category' => 'Catégorie de courrier',
    'Add Letter' => 'Ajouter un courrier',
    'Add Letter Category' => 'Ajouter une catégorie de courrier',
    'Rent Item' => 'Article de location',
    'Default Account' => 'Compte par défaut',
    'Default Debit Account' => 'Compte débit par défaut',
    'Default Credit Account' => 'Compte crédit par défaut',
    'Debit Account' => 'Compte débit',
    'Credit Account' => 'Compte crédit',
    '.' => '.',
    'Total Amount' => 'Montant total',
    'Due Amount' => 'Montant dû',
    'Deposit Payment' => 'Paiement d\'acompte',
    'Invoice Format' => 'Format de facture',
    'Transaction Reference' => 'Référence de transaction',
    'Batch No' => 'N° de lot',
    'This product has batch and expired date' => 'Ce produit a un lot et une date d\'expiration',
    'Reward Point Setting' => 'Paramètres des points de récompense',
    'Price change' => 'Changement de prix',
    'Sold amount per point' => 'Montant vendu par point',
    'Minumum sold amount to get point' => 'Montant minimum vendu pour obtenir un point',
    'Point Expiry Duration' => 'Durée d\'expiration des points',
    'Duration Type' => 'Type de durée',
    'This means how much point customer will get according to sold amount. For example, if you put 100 then for every 100 dollar spent customer will get one point as reward.' => 'Indique combien de points le client obtient selon le montant acheté. Par exemple, si vous mettez 100, pour chaque 100 dépensés le client reçoit un point.',
    'For example, if you put 100 then customer will only get point after spending 100 dollar or more.' => 'Par exemple, si vous mettez 100, le client n\'obtiendra un point qu\'après avoir dépensé 100 ou plus.',
    'Active reward point' => 'Points de récompense actifs',
    'Reward Points' => 'Points de récompense',
    'Average Report' => 'Rapport de consommation mensuelle moyenne',
    'AMC Report' => 'Rapport AMC',
    'JE Report' => 'Rapport JE',
    'JE method' => 'Méthode JE',
    'Multiple Batch' => 'Lots multiples',
    'Prepared By' => 'Préparé par',
    'Station Code' => 'Code station',
    'Initial page' => 'Page initiale',
    'The competition will culminate in a spectacular grand finale, where the remaining contestants will showcase their talent and compete for the top honors. The finale will be a grand celebration of music, featuring electrifying performances from captivating stage production, and guest appearances by renowned artists (The Prophetic Minstrel). The winners of Beyond the Talent Show will receive a range of prizes designed to support their musical journeys. These prizes will include , financial Rewards (500,000frs) recording contracts, music production opportunities, performance bookings, mentorship packages, and valuable connections within the music industry. Additionally, the exposure gained through the competition will open doors to new opportunities and propel the winners towards successful music careers' => 'La compétition culminera lors d\'une grande finale spectaculaire, où les candidats restants présenteront leur talent et se disputeront les premières places. La finale sera une grande célébration de la musique, avec des performances électrisantes, une mise en scène captivante et des apparitions d\'artistes renommés (The Prophetic Minstrel). Les gagnants recevront des prix pour soutenir leur parcours musical : récompenses financières (500 000 FCFA), contrats d\'enregistrement, opportunités de production, bookings, mentorat et connexions dans l\'industrie musicale.',
    'Show Stats' => 'Afficher les statistiques',
    'Tickets Sold' => 'Billets vendus',
    'Whatsapp number' => 'Numéro WhatsApp',
    'Momo Number' => 'Numéro MoMo',
    'Remaining Seats' => 'Sièges restants',
    'Announcement' => 'Annonce',
    'Create Announcement' => 'Créer une annonce',
    'Announcement List' => 'Liste des annonces',
    'Is Used' => 'Est utilisé',
    'Total Purchase Tickets' => 'Total des billets achetés',
    'Update Announcement' => 'Mettre à jour l\'annonce',
    'Available for Grading' => 'Disponible pour notation',
    // Frontend extras
    'Grand Champions' => 'Grands champions',
    'Our' => 'Nos',
    'Winners' => 'Gagnants',
    'Casting Tour' => 'Tournée de casting',
    'starts in' => 'commence dans',
    'Darg' => 'Glisser',
    'Switch Language' => 'Changer de langue',
    'Login to validate ticket' => 'Connectez-vous pour valider le billet',
];

$merged = array_merge($fr, $manual);
foreach (array_diff_key($en, $merged) as $key => $val) {
    $merged[$key] = $manual[$key] ?? $val; // fallback to EN if no manual entry
}

$lines = ["<?php\n", "return [\n"];
foreach ($merged as $key => $val) {
    $k = var_export($key, true);
    $v = var_export($val, true);
    $lines[] = "    {$k} => {$v},\n";
}
$lines[] = "];\n";

file_put_contents($frPath, implode('', $lines));
echo 'FR file updated: ' . count($merged) . " keys\n";
